Add app.zen_browser.zen and io.github.celluloid_player.Celluloid

diff --git a/.github/workflows/rebuild.yml b/.github/workflows/rebuild.yml
--- a/.github/workflows/rebuild.yml
+++ b/.github/workflows/rebuild.yml
@@ -36,6 +36,7 @@ jobs:
         with:
           repository: flathub/${{ matrix.app }}
           path: src
+          submodules: recursive
 
       - name: Import GPG key
         uses: crazy-max/ghaction-import-gpg@v5
@@ -51,11 +52,24 @@ jobs:
             git apply --directory src -p 2 "${patch}"
           done
 
+      - name: Find manifest
+        id: resolution
+        run: |
+          base="src/${{ matrix.app }}"
+          for ext in json yaml yml; do
+            if [ -f "${base}.${ext}" ]; then
+              echo "manifest=${base}.${ext}" >> ${GITHUB_OUTPUT}
+              exit 0
+            fi
+          done
+          echo "::error::No manifest found!" >&2
+          exit 1
+
       - name: Build flatpak
         uses: flatpak/flatpak-github-actions/flatpak-builder@v6
         with:
           build-bundle: false
-          manifest-path: src/${{ matrix.app }}.yml
+          manifest-path: ${{ steps.resolution.outputs.manifest }}
           gpg-sign: ${{ steps.importation.outputs.keyid }}
           cache-key: flatpak-builder-${{ matrix.app }}
 
@@ -63,13 +77,6 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: ${{ matrix.app }}
-          path: repo
-
-      # Remove this when there are multiple apps to build
-      - name: Upload artifact (Test)
-        uses: actions/upload-artifact@v4
-        with:
-          name: com.abc.def
           path: repo
 
   upload:
